name: Release

on:
    workflow_run:
        workflows: ['Create ARM']
        types: [completed]
        branches:
            - 'main'
permissions:
      id-token: write
      contents: read
      
jobs: 
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    
 # we 1st download the previously uploaded artifact so we can leverage it later in the release job     
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
           workflow: ${{ github.event.workflow_run.workflow_id }}
           workflow_conclusion: success

      - name: Login via Az module
        uses: azure/login@v2
        with:
          auth-type: IDENTITY
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true 

      - name: data-factory-deploy
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: practice-rg-stg # (6) your target ADF resource group name
          dataFactoryName: practice-adf-mebin-stg # (7) your target ADF name
          armTemplateFile: ExportedArmTemplate/ARMTemplateForFactory.json # (8) ARM template file name ARMTemplateForFactory.json
          armTemplateParametersFile: ExportedArmTemplate/ARMTemplateParametersForFactory.json # (9) ARM template parameters file name ARMTemplateParametersForFactory.json
          #additionalParameters: # (10) Parameters which will be replaced in the ARM template. Expected format 'key1=value key2=value keyN=value'. At the minimum here you should provide the target ADF name parameter. Check the ARMTemplateParametersForFactory.json file for all the parameters that are expected in your scenario
         
          # skipAzModuleInstallation:  # Parameters which skip the Az module installation. Optional, default is false.​
